workflows:
  expo-ios-workflow:
    name: Expo iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_creds # Store EXPO_TOKEN here if needed
      vars:
        XCODE_VERSION: 15.0
        BUNDLE_ID: "com.reya42.wewillsucceedtogether"
    scripts:
      - name: Set up environment
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform ios
      - name: Install Pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Launch Simulator
        script: |
          xcrun simctl boot "iPhone 15"
          open -a Simulator
          sleep 20
      - name: Build and Run
        script: |
          # Start Metro bundler in background
          npx expo start --dev-client &
          # Build and install
          xcodebuild -workspace ios/WeWillSucceedTogether.xcworkspace \
            -scheme WeWillSucceedTogether \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
          # Install and launch
          xcrun simctl install booted ios/build/Build/Products/Debug-iphonesimulator/WeWillSucceedTogether.app
          xcrun simctl launch booted $BUNDLE_ID