workflows:
  ios-simulator-test:
    name: iOS Simulator Test
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_VERSION: 15.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @react-native-community/cli
          cd ios && pod install && cd ..
      - name: Start Metro Bundler
        script: npm start &
      - name: List available simulators
        script: xcrun simctl list devices
      - name: Launch Simulator
        script: |
          xcrun simctl boot "iPhone 15"
          open -a Simulator
      - name: Build and run on simulator
        script: |
          export RCT_METRO_PORT=8081
          npx react-native run-ios --simulator="iPhone 15"