workflows:
  ios-simulator-test:
    name: iOS Simulator Test
    environment:
      node: 18.17.1
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build for iOS Simulator
        script: |
          eas build --platform ios --profile preview --non-interactive
      - name: Test on Simulator
        script: |
          # Download the built .app (replace URL with your EAS build artifact)
          curl -L -o app.zip https://url-to-your-eas-build.app.zip
          unzip app.zip -d ./ios-build
          
          # Boot iPhone 15 simulator
          xcrun simctl boot "iPhone 15"
          
          # Install and launch
          xcrun simctl install booted ./ios-build/WeWillSucceedTogether.app
          xcrun simctl launch booted com.wewillsucceed.together
    artifacts:
      - ios-build/**/*.app