workflows:
  ios-simulator-test:
    name: iOS Simulator Test
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_VERSION: 15.0 # Use latest stable version
    scripts:
      - name: Install Node dependencies
        script: npm install
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Start Metro Bundler in background
        script: npm start &
      - name: Launch iOS Simulator
        script: |
          xcrun simctl list devices
          xcrun simctl boot "iPhone 15" # or any device you want
          open -a Simulator
      - name: Build and run on simulator
        script: npx react-native run-ios --simulator="iPhone 15"