workflows:
  ios-simulator-test:
    name: iOS Simulator Test
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_VERSION: 15.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g expo-cli @react-native-community/cli
      - name: Prebuild iOS files
        script: npx expo prebuild --platform ios
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Start Expo dev server
        script: npx expo start --clear &
      - name: Launch iOS Simulator
        script: |
          xcrun simctl list devices
          xcrun simctl boot "iPhone 15"
          open -a Simulator
          sleep 15 # Wait for simulator to fully launch
      - name: Build and run on simulator
        script: |
          export RCT_METRO_PORT=8081
          npx expo start &
          sleep 15m